### ISSUE TITLE
connectivity code broken

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-sandbox#21]
@choldgraf could you take a look at the cfc code? MNE-Python has deprecated the `ctw_morlet` function, so now mne-sandbox doesn't work anymore due to an improper import.

**Comment by choldgraf** [comment]
ah crap, lemme take a look at it today if I have time, tomorrow otherwise.
I need to create a midterm for a class in 4 days first :P
--

**Comment by christianbrodbeck** [comment]
Unless I'm mistaken this has been fixed.

**Comment by choldgraf** [comment]
lol, I love how my inbox signature includes the `---` and then github interprets that as a header line...yep this has been fixed :)
