### ISSUE TITLE
Rename repository to mne-incubator

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-sandbox#33]
When it was first suggested to me to add some code to this repository, I felt very strongly against it, and I realize part of this objection was due to the repository's name. A "sandbox" can usually mean two things:

- a safe and isolated place where kids can go play without harming themselves or anyone else,
- a safe and isolated space provided by computer software or the operating system where potentially malicious actors are locked in so they cannot destroy the rest of the system

Code that isn't just quite ready for production, but should be worked on with the clear intention of getting integrated upstream sometime in the future falls into neither of these two categories: We're not kids playing, nor are we malicious (at least I hope so!); and **we do want to get this stuff production-ready** – at least that's what **I** want to do!

So what the `mne-sandbox` actually is supposed to be is some sort of a "laboratory" for new ideas, but with a clear path to get merged upstream if the experiments turn out to be fruitful, promising, and "ripe" for general use.

These kinds of repositories are commonly called **incubators**. See for example:

- [Apache Incubator](https://incubator.apache.org)
- [Mozilla Builders Incubator](https://builders.mozilla.community)
- [IBM Open-Source Incubator](https://research.ibm.com/collaborate/open-source-incubator)

just to name a few.

**I would therefore like to propose to change the name of this repository to `mne-incubator`** so at a single glance it becomes clear: this is not supposed to be a dusty attic where ideas are just being placed and forgotten, but that we're determined to bring the experiments happening here into production eventually.

**Comment by agramfort** [comment]
No strong feelings

**Comment by wmvanvliet** [comment]
> We're not kids playing

Speak for yourself ;) But no, no objections regarding the name change. This repo is not really actively used anyway. Nowadays, if I have some algorithm that is a bit experimental, I just make it a standalone package.

**Comment by drammock** [comment]
Let's plan to make this change next Tuesday (06 sept), unless someone objects in the meantime.

**Comment by drammock** [comment]
Done!

**Comment by drammock** [comment]
oops, not done.  All I did was change the repo name...  now to change all the code/docs
