### ISSUE TITLE
Bad channel/epoch detection

### ISSUE THREAD

**Issue by wmvanvliet** [mne-tools/mne-sandbox#6]
We should add the faster code to the sandbox at some point. If not the entire pipeline, at least functions like `detect_bad_channels`, `detect_bad_epochs` and `detect_bad_channels_in_epochs` are very useful.

**Comment by wmvanvliet** [comment]
Since the publication of [autoreject](http://www.sciencedirect.com/science/article/pii/S1053811917305013), I'm not so keen anymore to move ahead with FASTER.

**Comment by agramfort** [comment]
glad you've been converted to autoreject :)

**Comment by wmvanvliet** [comment]
I'm loving it so far! :)

**Comment by agramfort** [comment]
tweet and we'll retweet :)
